### ISSUE TITLE
Compiler error: async is a keyword

### ISSUE THREAD

**Issue by aquarial** [balisujohn/mltests#3]
I get a compiler error pointing to [visulization.py Line 60](https://github.com/balisujohn/mltests/blob/master/python_neuro_ev/visualization.py#L60) which passes `async = True` to a function.

`async` is a keyword in python now, so this won't compile. I deleted the argument locally and it seemed to work normally. 

```bash
[nix-shell] $ python3 --version
Python 3.7.3

[nix-shell] $ python3 ./base_SNN/main.py train cartpole default
Traceback (most recent call last):
  File "./base_SNN/main.py", line 1, in <module>
    import learning
  File "mltests/python_neuro_ev/base_SNN/learning.py", line 3, in <module>
    import brain
  File "mltests/python_neuro_ev/base_SNN/brain.py", line 14, in <module>
    import visualization 
  File "./visualization.py", line 60
    win = GraphWindow(g,pos, async = True,  geometry =(500,400) ,vertex_text=g.vertex_index, vertex_font_sizcolor = color_map)
                                 ^
SyntaxError: invalid syntax
```

**Comment by balisujohn** [comment]
This seems like a sensible change to make. My local development environment is on python 3.5.2, so I did not encounter that issue. If you want, feel free to pull request your change to master.
